//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace giaothong.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAOVIEN_GCN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIAOVIEN_GCN()
        {
            this.GIAOVIENs = new HashSet<GIAOVIEN>();
        }
    
        public string SoGCN { get; set; }
        public string QDCap { get; set; }
        public string DonViCap { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public string HangXe { get; set; }
        public string MaDonViTapHuan { get; set; }
        public Nullable<System.DateTime> NgayKiemTra { get; set; }
        public string AnhGCN { get; set; }
        public string NguoiCapNhat { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIAOVIEN> GIAOVIENs { get; set; }
    }
}
