//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace giaothong.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class XETAPLAI
    {
        public string SoDangKy { get; set; }
        public string TenChuSoHuu { get; set; }
        public string SoGPTL { get; set; }
        public string NhanHieu { get; set; }
        public string KieuLoai { get; set; }
        public string HangXe { get; set; }
        public string MauXe { get; set; }
        public string SoDongCo { get; set; }
        public string SoKhung { get; set; }
        public string NamSX { get; set; }
        public string LoaiXe { get; set; }
        public Nullable<bool> XeSatHach { get; set; }
        public Nullable<bool> TrangThaiHD { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string NguoiCapNhat { get; set; }
    
        public virtual XETAPLAI_GP XETAPLAI_GP { get; set; }
    }
}
