//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace giaothong.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class XETAPLAI_GP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XETAPLAI_GP()
        {
            this.XETAPLAIs = new HashSet<XETAPLAI>();
        }
    
        public string SoGPXTL { get; set; }
        public string SoDangKy { get; set; }
        public string MaDonViCap { get; set; }
        public string MaCSDT { get; set; }
        public Nullable<bool> XeHopDong { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public Nullable<System.DateTime> NgayHH { get; set; }
        public string AnhGP { get; set; }
        public string AnhDKiem { get; set; }
        public string AnhDky { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string NguoiCapNhat { get; set; }
        public string DuongTapLai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XETAPLAI> XETAPLAIs { get; set; }
    }
}
